---
- name: Configuración endurecida de SSH
  ansible.builtin.template:
    src: 10-hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/10-hardening.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reiniciar SSH

- name: Validar la configuración de SSH
  ansible.builtin.command: sshd -t
  changed_when: false
